.PHONY: all build test lint generate migrate-up migrate-down fmt vet tidy run proto

# Published binary name. Override to ship under a different name without
# touching the source tree, e.g. `make build BIN_NAME=storagesvc`.
# The Go package path stays cmd/server regardless.
BIN_NAME := storage-service
CMD_DIR  := cmd/server

# Build-time version info injected via -ldflags into internal/version.
VERSION   ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
COMMIT    ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
BRANCH    ?= $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
BUILDTIME := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
VERSION_PKG := github.com/servekit/storage-service/internal/version
LDFLAGS := -X $(VERSION_PKG).Version=$(VERSION) \
           -X $(VERSION_PKG).GitCommit=$(COMMIT) \
           -X $(VERSION_PKG).GitBranch=$(BRANCH) \
           -X $(VERSION_PKG).BuildTime=$(BUILDTIME)

## build: Build the storage-service binary (version info via -ldflags)
build:
	go build -ldflags "$(LDFLAGS)" -o bin/$(BIN_NAME) ./$(CMD_DIR)/

## run: Run the server locally
run:
	@test -f config.yaml || cp config.example.yaml config.yaml
	go run ./$(CMD_DIR)/

## test: Run tests with race detector
test:
	go test -race -coverprofile=coverage.out ./...

## lint: Run golangci-lint
lint:
	golangci-lint run ./...

## fmt: Format code
fmt:
	gofmt -w .
	goimports -w .

## vet: Run go vet
vet:
	go vet ./...

## generate: Run gorm.io/cli code generation
generate:
	gorm gen -i ./internal/store/models -o ./internal/store/generated

## proto: Generate protobuf code with buf
proto:
	buf generate

## migrate: Run database migrations (AutoMigrate) via the unified binary
migrate:
	@test -f config.yaml || cp config.example.yaml config.yaml
	go run ./$(CMD_DIR) migrate

## tidy: Run go mod tidy
tidy:
	go mod tidy

## all: Format, vet, lint, test
all: fmt vet lint test

# BEGIN service-docker-scaffold
# Generated by service-docker-scaffold. Rerendering replaces this entire block.

IMAGE_REPOSITORY ?= storage-service
IMAGE_TAG ?= latest
TARGET_PLATFORM ?=
DOCKER_PLATFORM_ENV = $(if $(strip $(TARGET_PLATFORM)),DOCKER_DEFAULT_PLATFORM=$(TARGET_PLATFORM))
DOCKER_COMPOSE := $(DOCKER_PLATFORM_ENV) IMAGE_REPOSITORY=$(IMAGE_REPOSITORY) IMAGE_TAG=$(IMAGE_TAG) docker compose

.PHONY: docker-build docker-push docker-up docker-migrate docker-down docker-reset docker-logs docker-health

## docker-build: Build the host platform, or pass TARGET_PLATFORM=linux/amd64
docker-build:
	$(DOCKER_COMPOSE) build

## docker-push: Push $(IMAGE_REPOSITORY):$(IMAGE_TAG)
docker-push: docker-build
	$(DOCKER_COMPOSE) push storage-service

## docker-up: Build and start the selected stack, then wait for healthchecks
docker-up: docker-build
	$(DOCKER_COMPOSE) up --wait --no-build -d

## docker-migrate: One-shot migration against the compose DB (builds, starts deps, runs migrate, exits)
docker-migrate: docker-build
	$(DOCKER_COMPOSE) run --rm storage-service migrate

## docker-down: Stop containers while preserving named volumes
docker-down:
	$(DOCKER_COMPOSE) down

## docker-reset: Stop containers and deliberately delete named volumes
docker-reset:
	@echo "Deleting Docker volumes for storage-service"
	$(DOCKER_COMPOSE) down -v

## docker-logs: Follow logs for all services, or pass svc=<service>
docker-logs:
	$(DOCKER_COMPOSE) logs -f --tail=100 $(svc)

## docker-health: Query grpcx health from inside the app container
docker-health:
	$(DOCKER_COMPOSE) exec -T storage-service grpc_health_probe -addr=127.0.0.1:19093

# END service-docker-scaffold
